execute: 
  cache: true

project: 
  type: website
  execute-dir: file
  output-dir: ../docs
  render:
    - "*.qmd"

format:
  html:
    theme: lux
    toc: true
    toc-depth: 3
    code-fold: true
    standalone: false
    embed-resources: false
    
website:
  title: DAS
  navbar:
    search: false
    left:
      - file: home.qmd
      #- sidebar:cytof
      #- sidebar:scrna
  #sidebar: 
    #- id: cytof
    #  title: CyTOF
    #  contents:
    #    - file: CyTOF.qmd
    #- id: scrna
    #  title: scRNA
    #  contents:
    #    - file: scRNA.qmd
    # - id: visium
    #   title: Visium
    #   contents: 
    #     - file: visium-01-exploratory.qmd
    #     - file: visium-02-downstream.qmd
    # - id: mapping
    #   title: Mapping
    #   contents: 
    #     - file: mapping-01-exploratory.qmd