---
title: "Case study on Kang18 scRNA-seq dataset"
format:
  html:
    toc: true
    code-fold: true
    code-tools: true
    toc_float: true
---

## Dependencies
```{r}
library(ExperimentHub)
library(scater)
library(muscat)
```

## Loading the data
```{r}
eh <- ExperimentHub()
query(eh, "Kang")
(sce <- eh[["EH2259"]])
```

## Data Preprocessing
```{r}
sce <- sce[rowSums(counts(sce) > 0) > 0, ]
qc <- perCellQCMetrics(sce)

# remove cells with few or many detected genes
ol <- isOutlier(metric = qc$detected, nmads = 2, log = TRUE)
sce <- sce[, !ol]

# remove lowly expressed genes
sce <- sce[rowSums(counts(sce) > 1) >= 10, ]

# compute sum-factors & normalize
sce <- computeLibraryFactors(sce)
sce <- logNormCounts(sce)
```

## Data preparation
```{r}
sce$id <- paste0(sce$stim, sce$ind)
(sce <- prepSCE(sce, 
    kid = "cell", # subpopulation assignments
    gid = "stim",  # group IDs (ctrl/stim)
    sid = "id",   # sample IDs (ctrl/stim.1234)
    drop = TRUE))  # drop all other colData columns
saveRDS(sce, "../../data/Kang/sce.rds")
```

